### ISSUE TITLE
JSON.stringify the result may generate error

### ISSUE THREAD

**Issue by eight04** [eight04/node_vm2#4]
https://github.com/eight04/node_vm2/blob/69ddd86bfb633d56cbe10bfaa676743d8dc14299/node_vm2/vm-server/index.js#L35

```
d:\dev\node_vm2\node_vm2\vm-server\index.js:35
                console.log(JSON.stringify(result));
                                 ^

TypeError: 'getOwnPropertyDescriptor' on proxy: trap returned descriptor for pro
perty 'userData' that is incompatible with the existing property in the proxy ta
rget
    at JSON.stringify (<anonymous>)
    at Interface.rl.on.line (d:\dev\node_vm2\node_vm2\vm-server\index.js:35:20)
    at Interface.emit (events.js:127:13)
    at Interface._onLine (readline.js:285:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:144:10)
    at Socket.emit (events.js:127:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
```

Ref: https://github.com/patriksimek/vm2/issues/136

**Comment by eight04** [comment]
Fixed in 0.3.2.
